name: Create Tag on Release Branch Push

on:
  push:
    branches:
      - release

permissions:
  actions: write
  checks: write
  contents: write

jobs:
  create_tag:
    runs-on: ubuntu-latest

    steps:
      - name: コードをチェックアウト
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # タグの作成とプッシュのために完全な履歴が必要

      - name: Gitユーザーを設定
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: タグを作成
        id: create_tag
        run: |
          TAG_NAME="release-$(date +'%Y%m%d%H%M%S')"
          git tag $TAG_NAME

      - name: タグをプッシュ
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin $TAG_NAME
